                                                                                                                                                                                                                                                                                                                                                             
#!/usr/bin/python shutdown/reboot(/power on) Raspberry Pi with pushbutton                                                                                                                                                                                                                                                                                    
###  SCRIPT IN ".bashrc" FILE CODE:                                                                                                                                                                                                                                                                                                                          
        # sudo nano /home/pi/.bashrc                                                                                                                                                                                                                                                                                                                         
        # script code                                                                                                                                                                                                                                                                                                                                        
        # sudo python /home/pi/POWER/BUTTON_POWER.py                                                                                                                                                                                                                                                                                                         
import RPi.GPIO as GPIO                                                                                                                                                                                                                                                                                                                                      
from subprocess import call                                                                                                                                                                                                                                                                                                                                  
from datetime import datetime                                                                                                                                                                                                                                                                                                                                
import time                                                                                                                                                                                                                                                                                                                                                  
from time import sleep                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                             
# pushbutton connected to this GPIO pin, using pin 5 also has the benefit of waking / powering up Raspberry                                                                                                                                                                                                                                                  
# Pi when button is pressed                                                                                                                                                                                                                                                                                                                                  
shutdownPin = 5                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                             
# if button pressed for at least this long then shut down. if less then reboot.                                                                                                                                                                                                                                                                              
shutdownMinSeconds = 3                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                             
# button debounce time in seconds                                                                                                                                                                                                                                                                                                                            
debounceSeconds = 0.01                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                             
# BUTTON SETUP                                                                                                                                                                                                                                                                                                                                               
GPIO.setmode(GPIO.BOARD)                                                                                                                                                                                                                                                                                                                                     
GPIO.setup(shutdownPin, GPIO.IN, pull_up_down=GPIO.PUD_UP)                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                             
buttonPressedTime = None                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                             
### GPIO PIN LED VARIABLE                                                                                                                                                                                                                                                                                                                                    
off_LED = 8                                                                                                                                                                                                                                                                                                                                                  
reboot_LED = 10                                                                                                                                                                                                                                                                                                                                              
power_LED = 32                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                             
### SLEEP TIME VARIABLE                                                                                                                                                                                                                                                                                                                                      
#SLEEP ON / OFF                                                                                                                                                                                                                                                                                                                                              
SLEEP_ON = 0.25                                                                                                                                                                                                                                                                                                                                              
SLEEP_OFF = 0.125                                                                                                                                                                                                                                                                                                                                            
# SLEEP PAUSE                                                                                                                                                                                                                                                                                                                                                
SLEEP_pause = 0.5                                                                                                                                                                                                                                                                                                                                            
# STARTUP BLINK LED                                                                                                                                                                                                                                                                                                                                          
SLEEP_start = 0.05                                                                                                                                                                                                                                                                                                                                           
# SLEEP BUTTON                                                                                                                                                                                                                                                                                                                                               
SLEEP_BUTTON = 0.25                                                                                                                                                                                                                                                                                                                                          
# STANDBY SLEEP                                                                                                                                                                                                                                                                                                                                              
SLEEP_STANDBY = 0.5                                                                                                                                                                                                                                                                                                                                          
# SLEEP LOOP                                                                                                                                                                                                                                                                                                                                                 
SLEEP_loop = 10                                                                                                                                                                                                                                                                                                                                              
fast_SLEEP_loop = 0.1                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                             
repeat = 3                                                                                                                                                                                                                                                                                                                                                   
START_repeat = 10                                                                                                                                                                                                                                                                                                                                            
CLEAR_repeat = 4                                                                                                                                                                                                                                                                                                                                             
POWER_LED_repeat = 6                                                                                                                                                                                                                                                                                                                                         
BUTTON_repeat = 3                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                             
# LED GPIO SETUP                                                                                                                                                                                                                                                                                                                                             
GPIO.setwarnings(False)                                                                                                                                                                                                                                                                                                                                      
GPIO.setmode(GPIO.BOARD)                                                                                                                                                                                                                                                                                                                                     
GPIO.setup(off_LED, GPIO.OUT, initial=GPIO.LOW)                                                                                                                                                                                                                                                                                                              
GPIO.setup(reboot_LED, GPIO.OUT, initial=GPIO.LOW)                                                                                                                                                                                                                                                                                                           
GPIO.setup(power_LED, GPIO.OUT, initial=GPIO.LOW)                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                             
def SHUTDOWN_BLINK():                                                                                                                                                                                                                                                                                                                                        
    # SHUTDOWN BLINK                                                                                                                                                                                                                                                                                                                                         
    y = START_repeat                                                                                                                                                                                                                                                                                                                                         
    shut_times = 0                                                                                                                                                                                                                                                                                                                                           
    while shut_times < y:                                                                                                                                                                                                                                                                                                                                    
    # blink shutdown                                                                                                                                                                                                                                                                                                                                         
        GPIO.output(off_LED, GPIO.HIGH)                                                                                                                                                                                                                                                                                                                      
        sleep(SLEEP_start)                                                                                                                                                                                                                                                                                                                                   
        GPIO.output(off_LED, GPIO.LOW)                                                                                                                                                                                                                                                                                                                       
        sleep(SLEEP_start)                                                                                                                                                                                                                                                                                                                                   
        shut_times = shut_times + 1                                                                                                                                                                                                                                                                                                                          
    GPIO.output(off_LED, GPIO.HIGH)                                                                                                                                                                                                                                                                                                                          
    print("shutdown blink")                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                             
def REBOOT_BLINK():                                                                                                                                                                                                                                                                                                                                          
    # REBOOT BLINK                                                                                                                                                                                                                                                                                                                                           
    y = START_repeat                                                                                                                                                                                                                                                                                                                                         
    reboot_times = 0                                                                                                                                                                                                                                                                                                                                         
    while reboot_times < y:                                                                                                                                                                                                                                                                                                                                  
    # blink shutdown                                                                                                                                                                                                                                                                                                                                         
        GPIO.output(reboot_LED, GPIO.HIGH)                                                                                                                                                                                                                                                                                                                   
        sleep(SLEEP_start)                                                                                                                                                                                                                                                                                                                                   
        GPIO.output(reboot_LED, GPIO.LOW)                                                                                                                                                                                                                                                                                                                    
        sleep(SLEEP_start)                                                                                                                                                                                                                                                                                                                                   
        reboot_times = reboot_times + 1                                                                                                                                                                                                                                                                                                                      
    GPIO.output(reboot_LED, GPIO.HIGH)                                                                                                                                                                                                                                                                                                                       
    print("reboot blink")                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                             
def POWER_BLINK():                                                                                                                                                                                                                                                                                                                                           
    # POWER BLINK                                                                                                                                                                                                                                                                                                                                            
    y = START_repeat                                                                                                                                                                                                                                                                                                                                         
    power_times = 0                                                                                                                                                                                                                                                                                                                                          
    while power_times < y:                                                                                                                                                                                                                                                                                                                                   
    # blink shutdown                                                                                                                                                                                                                                                                                                                                         
        GPIO.output(power_LED, GPIO.HIGH)                                                                                                                                                                                                                                                                                                                    
        sleep(SLEEP_start)                                                                                                                                                                                                                                                                                                                                   
        GPIO.output(power_LED, GPIO.LOW)                                                                                                                                                                                                                                                                                                                     
        sleep(SLEEP_start)                                                                                                                                                                                                                                                                                                                                   
        power_times = power_times + 1                                                                                                                                                                                                                                                                                                                        
    GPIO.output(reboot_LED, GPIO.HIGH)                                                                                                                                                                                                                                                                                                                       
    print("power blink")                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                             
def POWER_STANDBY():                                                                                                                                                                                                                                                                                                                                         
    GPIO.output(reboot_LED, GPIO.LOW)                                                                                                                                                                                                                                                                                                                        
    GPIO.output(off_LED, GPIO.LOW)                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                             
def BUTTON_REBOOT():                                                                                                                                                                                                                                                                                                                                         
    # REBOOT BUTTON                                                                                                                                                                                                                                                                                                                                          
    y = BUTTON_repeat                                                                                                                                                                                                                                                                                                                                        
    reboot_times = 0                                                                                                                                                                                                                                                                                                                                         
    while reboot_times < y:                                                                                                                                                                                                                                                                                                                                  
    # blink shutdown                                                                                                                                                                                                                                                                                                                                         
        GPIO.output(reboot_LED, GPIO.HIGH)                                                                                                                                                                                                                                                                                                                   
        sleep(SLEEP_BUTTON)                                                                                                                                                                                                                                                                                                                                  
        GPIO.output(reboot_LED, GPIO.LOW)                                                                                                                                                                                                                                                                                                                    
        sleep(SLEEP_BUTTON)                                                                                                                                                                                                                                                                                                                                  
        reboot_times = reboot_times + 1                                                                                                                                                                                                                                                                                                                      
    GPIO.output(power_LED, GPIO.HIGH)                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                             
def BUTTON_SHUTDOWN():                                                                                                                                                                                                                                                                                                                                       
    # REBOOT BUTTON                                                                                                                                                                                                                                                                                                                                          
    y = BUTTON_repeat                                                                                                                                                                                                                                                                                                                                        
    shut_times = 0                                                                                                                                                                                                                                                                                                                                           
    while shut_times < y:                                                                                                                                                                                                                                                                                                                                    
    # blink shutdown                                                                                                                                                                                                                                                                                                                                         
        GPIO.output(off_LED, GPIO.HIGH)                                                                                                                                                                                                                                                                                                                      
        sleep(SLEEP_BUTTON)                                                                                                                                                                                                                                                                                                                                  
        GPIO.output(off_LED, GPIO.LOW)                                                                                                                                                                                                                                                                                                                       
        sleep(SLEEP_BUTTON)                                                                                                                                                                                                                                                                                                                                  
        shut_times = shut_times + 1                                                                                                                                                                                                                                                                                                                          
    GPIO.output(power_LED, GPIO.HIGH)                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                             
def power_loop():                                                                                                                                                                                                                                                                                                                                            
    GPIO.output(power_LED, GPIO.HIGH)                                                                                                                                                                                                                                                                                                                        
    sleep(SLEEP_loop)                                                                                                                                                                                                                                                                                                                                        
    while 5 < 6:                                                                                                                                                                                                                                                                                                                                             
        print("power loop")                                                                                                                                                                                                                                                                                                                                  
        GPIO.output(power_LED, GPIO.HIGH)                                                                                                                                                                                                                                                                                                                    
        sleep(SLEEP_loop)                                                                                                                                                                                                                                                                                                                                    
        GPIO.output(power_LED, GPIO.LOW)                                                                                                                                                                                                                                                                                                                     
        sleep(fast_SLEEP_loop)                                                                                                                                                                                                                                                                                                                               
        GPIO.output(power_LED, GPIO.HIGH)                                                                                                                                                                                                                                                                                                                    
        sleep(fast_SLEEP_loop)                                                                                                                                                                                                                                                                                                                               
        GPIO.output(power_LED, GPIO.LOW)                                                                                                                                                                                                                                                                                                                     
        sleep(fast_SLEEP_loop)                                                                                                                                                                                                                                                                                                                               
        GPIO.output(power_LED, GPIO.HIGH)                                                                                                                                                                                                                                                                                                                    
        sleep(fast_SLEEP_loop)                                                                                                                                                                                                                                                                                                                               
        GPIO.output(power_LED, GPIO.LOW)                                                                                                                                                                                                                                                                                                                     
        sleep(fast_SLEEP_loop)                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                             
def STARTUP_BLINK():                                                                                                                                                                                                                                                                                                                                         
    SHUTDOWN_BLINK()                                                                                                                                                                                                                                                                                                                                         
    REBOOT_BLINK()                                                                                                                                                                                                                                                                                                                                           
    POWER_BLINK()                                                                                                                                                                                                                                                                                                                                            
    POWER_STANDBY()                                                                                                                                                                                                                                                                                                                                          
    sleep(SLEEP_STANDBY)                                                                                                                                                                                                                                                                                                                                     
    print("    ")                                                                                                                                                                                                                                                                                                                                            
    print("    ")                                                                                                                                                                                                                                                                                                                                            
    print("    STANDBY")                                                                                                                                                                                                                                                                                                                                     
    GPIO.output(power_LED, GPIO.HIGH)                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                             
STARTUP_BLINK()                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                             
def buttonStateChanged(pin):                                                                                                                                                                                                                                                                                                                                 
    global buttonPressedTime                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                             
    if not (GPIO.input(pin)):                                                                                                                                                                                                                                                                                                                                
        # button is down                                                                                                                                                                                                                                                                                                                                     
        if buttonPressedTime is None:                                                                                                                                                                                                                                                                                                                        
            buttonPressedTime = datetime.now()                                                                                                                                                                                                                                                                                                               
    else:                                                                                                                                                                                                                                                                                                                                                    
        # button is up                                                                                                                                                                                                                                                                                                                                       
        if buttonPressedTime is not None:                                                                                                                                                                                                                                                                                                                    
            elapsed = (datetime.now() - buttonPressedTime).total_seconds()                                                                                                                                                                                                                                                                                   
            buttonPressedTime = None                                                                                                                                                                                                                                                                                                                         
            if elapsed >= shutdownMinSeconds:                                                                                                                                                                                                                                                                                                                
                # button pressed for more than specified time, shutdown                                                                                                                                                                                                                                                                                      
                ## SHUTDOWN BLINK                                                                                                                                                                                                                                                                                                                            
                BUTTON_SHUTDOWN()                                                                                                                                                                                                                                                                                                                            
                print("    ")                                                                                                                                                                                                                                                                                                                                
                print("    ")                                                                                                                                                                                                                                                                                                                                
                print("    SHUTDOWN")                                                                                                                                                                                                                                                                                                                        
                sleep(SLEEP_pause)                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                             
### add # to 3rd line down to edit                                                                                                                                                                                                                                                                                                                           
                call(['shutdown', '-h', 'now'], shell=False)                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                             
            elif elapsed >= debounceSeconds:                                                                                                                                                                                                                                                                                                                 
                # button pressed for a shorter time, reboot                                                                                                                                                                                                                                                                                                  
                ## REBOOT BLINK                                                                                                                                                                                                                                                                                                                              
                ### add # to 3rd line down to edit                                                                                                                                                                                                                                                                                                           
                BUTTON_REBOOT()                                                                                                                                                                                                                                                                                                                              
                print("    ")                                                                                                                                                                                                                                                                                                                                
                print("    ")                                                                                                                                                                                                                                                                                                                                
                print("    REBOOT")                                                                                                                                                                                                                                                                                                                          
                sleep(SLEEP_pause)                                                                                                                                                                                                                                                                                                                           
                call(['shutdown', '-r', 'now'], shell=False)                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                             
# subscribe to button presses                                                                                                                                                                                                                                                                                                                                
GPIO.add_event_detect(shutdownPin, GPIO.BOTH, callback=buttonStateChanged)                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                             
while True:                                                                                                                                                                                                                                                                                                                                                  
    # sleep to reduce unnecessary CPU usage                                                                                                                                                                                                                                                                                                                  
    sleep(5)
